name: Test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - snapshot
    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Setup Eldev
        uses: emacs-eldev/setup-eldev@v1
      - name: Checkout source code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Tests with coverage
        run: eldev -C -dTv test -u on,text
      - name: Tests on packaged
        run: eldev -C -dpTv test
      - name: Compile
        run: eldev -C -dpTv compile -W
      - name: Lint
        run: eldev -C -dpTv lint
      - name: Eldev Doctor
        run: eldev -C -dpTv doctor
