name: Test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - snapshot
    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Setup Eldev
        uses: emacs-eldev/setup-eldev@v1

      - name: Checkout source code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: eldev/test
        run: eldev --color=always --debug --packaged --time --verbose test

      - name: eldev/compile
        run: eldev --color=always --debug --packaged --time --verbose compile --warnings-as-errors

      - name: eldev/lint
        run: eldev --color=always --debug --packaged --time --verbose lint

      - name: eldev/doctor
        run: eldev --color=always --debug --packaged --time --verbose doctor
